language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
addons:
  postgresql: "9.3"
before_install:
  - sudo service postgresql start 9.3
  - CONFIG_FILE=$(sudo -u postgres psql postgres -c "SHOW config_file;" -q -t | head -1)
  - echo "Postgresql config file is $CONFIG_FILE"
  - echo "max_prepared_transactions = 10" | sudo tee -a "$CONFIG_FILE"
  - sudo cat "$CONFIG_FILE"
  - sudo service postgresql restart 9.3
install:
  - python setup.py sdist --formats=zip
  - pip install dist/*.zip
  - pip install coveralls
before_script:
  - psql template1 -c 'CREATE EXTENSION "uuid-ossp";' -U postgres
  - psql -c 'CREATE DATABASE test_yithlibrary;' -U postgres
script:
  - coverage run --source=yithlibraryserver setup.py test
after_success:
  - coveralls
services:
  - postgresql
