language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "pypy"
addons:
  postgresql: "9.3"
before_install:
  - CONFIG_FILE=$(sudo -u postgres psql postgres -c "SHOW config_file;" -q -t | head -1)
  - 'CONFIG_FILE="${CONFIG_FILE:1}"'
  - echo "max_prepared_transactions = 10" | sudo tee -a "$CONFIG_FILE"
  - sudo cat "$CONFIG_FILE"
  - sudo service postgresql restart 9.3
install:
  - python setup.py develop
  - pip install coveralls
before_script:
  - if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then psql -c 'CREATE DATABASE test_yithlibrary_cpython_26; CREATE EXTENSION "uuid-ossp";' -U postgres; fi
  - if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then psql -c 'CREATE DATABASE test_yithlibrary_cpython_27; CREATE EXTENSION "uuid-ossp";' -U postgres; fi
  - if [[ $TRAVIS_PYTHON_VERSION == '3.3' ]]; then psql -c 'CREATE DATABASE test_yithlibrary_cpython_33; CREATE EXTENSION "uuid-ossp";' -U postgres; fi
  - if [[ $TRAVIS_PYTHON_VERSION == '3.4' ]]; then psql -c 'CREATE DATABASE test_yithlibrary_cpython_34; CREATE EXTENSION "uuid-ossp";' -U postgres; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 'pypy' ]]; then psql -c 'CREATE DATABASE test_yithlibrary_pypy_27; CREATE EXTENSION "uuid-ossp";' -U postgres; fi
script:
  - coverage run --source=yithlibraryserver setup.py test
after_success:
  - coveralls
services:
  - mongodb
  - postgresql
