language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
install:
  - python setup.py develop
  - python setup.py testing
  - pip install coveralls
script:
  - nosetests --nocapture --with-coverage --cover-package=yithlibraryserver
after_success
  - coveralls
services:
  - mongodb
