language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "pypy"
install:
  - python setup.py develop
  - pip install coveralls
script:
  - coverage run --source=yithlibraryserver setup.py test
after_success:
  - coveralls
services:
  - mongodb
