language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "pypy"
addons:
  postgresql: "9.3"
install:
  - python setup.py develop
  - pip install coveralls
before_script:
  - if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then psql -c 'create database test_yithlibrary_cpython_26;' -U postgres; fi
  - if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then psql -c 'create database test_yithlibrary_cpython_27;' -U postgres; fi
  - if [[ $TRAVIS_PYTHON_VERSION == '3.3' ]]; then psql -c 'create database test_yithlibrary_cpython_33;' -U postgres; fi
  - if [[ $TRAVIS_PYTHON_VERSION == '3.4' ]]; then psql -c 'create database test_yithlibrary_cpython_34;' -U postgres; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 'pypy' ]]; then psql -c 'create database test_yithlibrary_pypy_27;' -U postgres; fi
script:
  - coverage run --source=yithlibraryserver setup.py test
after_success:
  - coveralls
services:
  - mongodb
  - postgresql
